[
    ["main.py 19",
    "TimeoutError",      
    "Traceback (most recent call last):\n  File \"main.py\", line 19, in <module>\n    raise TimeoutError()\nTimeoutError\n",
    "Время ожидания истекло"
    ],
    ["main.py 23", 
    "KeyError",
    "Traceback (most recent call last):\n  File \"main.py\", line 23, in <module>\n    raise KeyError()\nKeyError\n",
    "Ключ, указанный вами, не найден"
    ],
    ["main.py 27", 
    "TypeError",
    "Traceback (most recent call last):\n  File \"main.py\", line 27, in <module>\n    raise TypeError()\nTypeError\n",
    "Неверный тип данных"],
    ["main.py 31", 
    "IndexError",
    "Traceback (most recent call last):\n  File \"main.py\", line 31, in <module>\n    raise IndexError()\nIndexError\n",
    "Индекс вышел за пределы последовательности"
    ],
    ["main.py 35", 
    "ImportError",
    "Traceback (most recent call last):\n  File \"main.py\", line 35, in <module>\n    raise ImportError()\nImportError\n",
    "Ошибка иморта библиотеки, попробуйте pip"
    ]
]